"""Repository Notebook — local SQLite notes linked to registry repositories."""

from hub.notebook.db import NotebookDatabase, default_notebook_db_path
from hub.notebook.markdown_util import render_markdown
from hub.notebook.missions import MissionControl, mission_control
from hub.notebook.models import (
    DEFAULT_SCOPE,
    DEFAULT_WORKSPACE,
    MISSION_REMINDER_BEFORE_HOUR,
    NOTE_TYPE_LABELS,
    NOTE_TYPES,
    PRIORITIES,
    PRIORITY_LABELS,
    REMINDER_STATUS_LABELS,
    REMINDER_STATUSES,
    REPO_ROLE_LABELS,
    REPO_ROLES,
    SCOPE_LABELS,
    SCOPES,
    STATUS_LABELS,
    STATUSES,
    WORKSPACES,
    normalize_scope,
    normalize_workspace,
)
from hub.notebook.notepad import (
    DEFAULT_WIDTH,
    FORMATS as NOTEPAD_FORMATS,
    MAX_WIDTH,
    MIN_WIDTH,
    NOTEPAD_IDS,
    PANEL_SIZES as NOTEPAD_PANEL_SIZES,
    QuickNotepadStore,
    normalize_panel_size,
)
from hub.notebook.store import NotebookStore

__all__ = [
    "DEFAULT_SCOPE",
    "DEFAULT_WORKSPACE",
    "MISSION_REMINDER_BEFORE_HOUR",
    "MissionControl",
    "NOTE_TYPE_LABELS",
    "NOTE_TYPES",
    "NOTEPAD_FORMATS",
    "NOTEPAD_PANEL_SIZES",
    "PRIORITIES",
    "PRIORITY_LABELS",
    "REMINDER_STATUS_LABELS",
    "REMINDER_STATUSES",
    "REPO_ROLE_LABELS",
    "REPO_ROLES",
    "SCOPE_LABELS",
    "SCOPES",
    "STATUS_LABELS",
    "STATUSES",
    "WORKSPACES",
    "DEFAULT_WIDTH",
    "MAX_WIDTH",
    "MIN_WIDTH",
    "NOTEPAD_IDS",
    "NotebookDatabase",
    "NotebookStore",
    "QuickNotepadStore",
    "default_notebook_db_path",
    "mission_control",
    "normalize_panel_size",
    "normalize_scope",
    "normalize_workspace",
    "render_markdown",
]
